apiVersion: apps/v1
kind: Deployment
metadata: { name: gateway }
spec:
  replicas: 3
  selector: { matchLabels: { app: gateway } }
  template:
    metadata: { labels: { app: gateway } }
    spec:
      containers:
      - name: gateway
        image: ghcr.io/example/recsys-llm/gateway:latest
        ports: [{ containerPort: 8080 }]
---
apiVersion: v1
kind: Service
metadata: { name: gateway }
spec:
  selector: { app: gateway }
  ports: [{ port: 80, targetPort: 8080 }]
